// Package code generated by "codegen -type=int"; DO NOT EDIT.
package code

// init register error codes defines in this source code to `github.com/EachinChung/errors`
func init() {
	register(ErrSuccess, 200, "success")
	register(ErrUnknown, 500, "服务器内部错误")
	register(ErrValidation, 400, "参数验证失败")
	register(ErrPageNotFound, 404, "资源不存在")
	register(ErrTokenInvalid, 401, "Token 不合法")
	register(ErrInvalidAuthHeader, 401, "Authorization 不合法")
	register(ErrMissingAuthHeader, 401, "Authorization 是空的")
	register(ErrUsernameOrPasswordIncorrect, 401, "账号或密码错误")
	register(ErrPermissionDenied, 403, "没有权限")
	register(ErrFailedTokenCreation, 401, "token 创建失败")
	register(ErrExpiredToken, 401, "token 已过期, 无法刷新")
	register(ErrMissingExpField, 400, "缺少 exp 字段")
	register(ErrWrongFormatOfExp, 400, "exp 必须是 float64 格式")
	register(ErrEmptyToken, 401, "没有携带 token")
	register(ErrInvalidSigningAlgorithm, 400, "无效签名算法")
	register(ErrFailedAuthentication, 401, "用户名或密码不正确")
	register(ErrDatabase, 500, "数据库错误")
	register(ErrUserAlreadyExist, 400, "用户已存在")
	register(ErrUserNotExist, 404, "用户不存在")
	register(ErrUsernameAlreadyExist, 400, "用户名已存在")
	register(ErrPhoneAlreadyExist, 400, "该手机号码已注册")
	register(ErrEmailAlreadyExist, 400, "该邮箱已注册")
	register(ErrUserStatusIsAbnormal, 403, "用户状态异常")
}
