// Package code generated by "codegen -type=int"; DO NOT EDIT.
package code

// init register error codes defines in this source code to `github.com/EachinChung/errors`
func init() {
	register(ErrUnknown, 500, "服务器内部错误")
	register(ErrValidation, 400, "参数验证失败")
	register(ErrPageNotFound, 404, "资源不存在")
	register(ErrPermissionDenied, 403, "没有权限")
	register(ErrNeedCaptcha, 403, "请验证您不是机器人")
	register(ErrCaptchaVerifyFailed, 400, "验证码校验失败")
	register(ErrCaptchaBusy, 500, "验证码服务繁忙, 请稍后再试")
	register(ErrFailedTokenCreation, 500, "token 创建失败")
	register(ErrEmptyToken, 401, "没有携带 token")
	register(ErrInvalidToken, 401, "Token 无效")
	register(ErrExpiredToken, 401, "token 已过期")
	register(ErrFailedAuthentication, 400, "账号或密码不正确")
	register(ErrNetworkUnsafe, 403, "网络环境不安全")
	register(ErrDatabase, 500, "数据库错误")
	register(ErrUserAlreadyExist, 400, "用户已存在")
	register(ErrUserNotExist, 404, "用户不存在")
	register(ErrUsernameAlreadyExist, 400, "用户名已存在")
	register(ErrPhoneAlreadyExist, 400, "该手机号码已注册")
	register(ErrEmailAlreadyExist, 400, "该邮箱已注册")
	register(ErrUserStatusIsAbnormal, 403, "用户状态异常")
}
