[server]
mode = "debug"
healthz = true
middlewares = ["LoggerWithColor", "Options", "Cors", "Secure", "NoCache"]
trusted-proxies = "127.0.0.1"
bind-address = "127.0.0.1"
bind-port = 8080

[jwt]
realm = "JWT"
key = "iqiLZuFgP9Ofc23egs4FSH57pyJ7"
timeout = "1h"
max-refresh = "360h"

[mysql]
host = "127.0.0.1:3306"
username = "root"
password = 123456
database = "e-service"
max-idle-connections = 100
max-open-connections = 100
max-connection-life-time = "60s"
log-level = 4
log-enable-color = true

[redis]
host = "127.0.0.1"
port = 6379
password = 123456

[log]
name = "e-service"
development = true
level = "debug"
format = "console"
enable-color = true
enable-full-caller = true
disable-caller = false
disable-stacktrace = false
output-paths = "stdout"
error-output-paths = "stderr"
